name: Use Friday Templates Workflow

on:
  workflow_dispatch:
    inputs:
      template-repo:
        description: 'The repository containing the Friday Templates workflow'
        required: false
        default: 'P4dr4/Friday-Templates'

jobs:
  use-friday-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Friday Templates Workflow
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.template-repo }}
          token: ${{ secrets.PAT }} # Use your Personal Access Token here
          fetch-depth: 0 # To fetch all history
          persist-credentials: false # Don't persist the fetched credentials to disk for future steps

  use-friday-angular:
    needs: [use-friday-templates]
    runs-on: ubuntu-latest
    steps:
      - name: Commit and Push Changes
        run: |
            cd "${{ github.workspace }}/my-angular-app"  # Navigate to the directory of your Angular application
            git add .
            export GPG_TTY=$(tty)
            gpg --batch --pinentry-mode loopback --passphrase-file "${{ github.workspace }}/passphrase.txt" --sign -a -s
            git commit -m "Add Angular application"
            git push origin master
    
      - name: Run Angular Scaffold 
        uses: ./.github/workflows/angular-scaffolding.yml@main
