name: Use Friday Templates Workflow

on:
  workflow_dispatch:
    inputs:
      template-repo:
        description: 'The repository containing the Friday Templates workflow'
        required: true
        default: 'P4dr4/Friday-Templates'

jobs:
  use-friday-templates:
    runs-on: ubuntu-latest
    needs: []

    steps:
      - name: Trigger Friday Templates Workflow
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.template-repo }}
          token: ${{ secrets.GITHUB_TOKEN }}

  use-friday-angular:
    runs-on: ubuntu-latest
    needs: [use-friday-templates]
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Angular Scaffold
        uses: P4dr4/Angular-app/.github/workflows/angular-scaffolding.yml@main
